main:
  projects:
    - title: "Quantum Quest: A High Schooler's Physics Adventure"
      authors: Chinmay Bharathulwar
      description: |
        A 100-page book introducing high school students to the core ideas of theoretical physics — from wave mechanics to black holes. Written to make abstract physics concepts accessible and engaging for young learners.
      pdf: /files/quantum_quest_sample.pdf
      external_link: https://www.amazon.com/dp/your-book-id
      image: ./assets/img/quantumquest.jpg
      notes: Amazon #1 Bestseller in Wave Mechanics and Gravity
      type: Book

    - title: "Motion and Metrics: Exploring Physics in Sports"
      description: |
        A blog exploring the intersection of physics, sports, and strategy. covering topics like the angular momentum of a basketball shot, the fluid dynamics of F1 aerodynamics, and the biomechanics behind elite athletic performance.
      link: https://motionandmetrics.example.com
      image: ./assets/img/motionandmetrics.png
      notes: Ongoing — new articles published monthly
      type: Blog
